all: snazzy.a test
CC = m6809-unknown-gcc
CFLAGS = -Os -DBARE
AR = m6809-unknown-ar
LD = m6809-unknown-ld
AS = m6809-unknown-as
SRC = snazzy.c label.c button.c ll-coco.c font.c poplist.c hslide.c panel.c
SRC += menu.c window.c text.c joy.c keyboard.c
OBJ = $(SRC:.c=.o)

$(OBJ): $(SRC)

snazzy.a: $(OBJ) snazzy.h ll.h test.frm
	$(AS) -o joyll.o joyll.s
	$(AS) -o graf.o graf.s
	$(AR) -rc snazzy.a $(OBJ) joyll.o graf.o
	rm -f $(OBJ)

test: snazzy.a test-coco.c crt0.s graf.s joyll.s joy.c
	$(AS) -o crt0.o crt0.s
	$(CC) $(CCFLAGS) -c test-coco.c
	lwlink -s basic.link -m test.map -o test.bin crt0.o test-coco.o \
	graf.o snazzy.a

test.dsk: test.bin
	decb2 mkfs test.dsk
	decb2 label test.dsk "SNAZZY GUI"
	decb2 put -l0a test.dsk autoexec.bas AUTOEXEC.BAS
	decb2 put -2b test.dsk test.bin TEST.BIN


test.frm: guipe/guipe guipe/test.rc
	cd guipe; ./guipe > ../test.frm

guipe/guipe:  guipe/guipe.c
	$(MAKE) -C guipe all

clean:
	rm -f *.o snazzy *~ test.h test.frm test snazzy.a test.bin test.map \
	test.dsk
	$(MAKE) -C guipe clean
