all: snazzy.a test
CC = m6809-unknown-gcc
CCFLAGS = -Os
AR = m6809-unknown-ar
LD = m6809-unknown-ld
AS = m6809-unknown-as
SRC = snazzy.c label.c button.c ll-coco.c font.c poplist.c hslide.c panel.c
SRC += menu.c window.c text.c
OBJ = $(SRC:.c=.o)

snazzy.a: $(SRC) snazzy.h ll.h test.frm
	$(CC) $(CCFLAGS) -c snazzy.c
	$(CC) $(CCFLAGS) -c label.c
	$(CC) $(CCFLAGS) -c button.c
	$(CC) $(CCFLAGS) -c ll-coco.c
	$(CC) $(CCFLAGS) -c font.c
	$(CC) $(CCFLAGS) -c poplist.c
	$(CC) $(CCFLAGS) -c hslide.c
	$(CC) $(CCFLAGS) -c panel.c
	$(CC) $(CCFLAGS) -c menu.c
	$(CC) $(CCFLAGS) -c window.c
	$(CC) $(CCFLAGS) -c text.c
	$(AR) -rc snazzy.a $(OBJ)
	rm -f $(OBJ)

test: snazzy.a test-coco.c crt0.s
	$(AS) -o crt0.o crt0.s
	$(CC) $(CCFLAGS) -c test-coco.c
	lwlink -s basic.link -m test.map -o test.bin crt0.o test-coco.o snazzy.a



test.frm: guipe/guipe guipe/test.rc
	cd guipe; ./guipe > ../test.frm

guipe/guipe:  guipe/guipe.c
	$(MAKE) -C guipe all

clean:
	rm -f *.o snazzy *~ test.h test.frm test snazzy.a test.bin test.map
	$(MAKE) -C guipe clean
